### ISSUE TITLE
question about yolov8

### ISSUE THREAD

**Issue by JingYuchen9** [ImaadHasan2002/Road-Segmentation-Object-Detection-using-Deep-Learning#1]
Hey guy I am new to computer vision. In this project how did you integrate resnet101 with yolov8, I didn't see any import file about Ultralytics :)

**Comment by ImaadHasan2002** [comment]
Hey there, we're planning to release the code once we've completed the necessary paperwork.

**Comment by JingYuchen9** [comment]
okay, thank you for reply~
